import * as THREE from "three";
import { WORLD_SCALE, PROP_SCALE } from "../../constants";
import type { Rect } from "../../geometry/floorplan";
import { HOUSE_B_PROPS, GARDEN_PROPS, type PropName, type PropPlacement, type Rot } from "./propManifest";
import { createPropInstance, FOOTPRINTS } from "./PropLibrary";
import { buildInstancedProps } from "./InstancedPropBuilder";
import { heightAt } from "./HeightField";

// Prop names placed at least this many times (across both mirrored houses +
// garden) render as InstancedMesh instead of one Object3D clone per
// placement - see InstancedPropBuilder for why that saves draw calls. Below
// the threshold, the per-placement Object3D approach is simpler and the
// draw-call cost is negligible; at/above it (trees, bushes, fences, crates,
// jail bars, stone path tiles, rugs all clear this today) instancing is a
// measurable win. Picked empirically against the current manifest, not a
// hard rule - revisit if placement counts change a lot.
const INSTANCE_THRESHOLD = 4;

// Pre-scale floor plan width (see geometry/floorplan.ts), used only to mirror
// house B's placements onto house A - never multiplied by WORLD_SCALE itself.
const FLOORPLAN_WIDTH = 1600;

function mirrorRot(rot: Rot): Rot {
  return (((360 - rot) % 360) as Rot);
}

function mirrorPlacement(p: PropPlacement): PropPlacement {
  return { ...p, x: FLOORPLAN_WIDTH - p.x, rot: mirrorRot(p.rot) };
}

// Axis-aligned collider rect for one solid placement, in SCALED world
// coords: the meter footprint * PROP_SCALE, swapped when rotated a quarter
// turn, centered on the placement's scaled position.
function solidRect(p: PropPlacement): Rect | null {
  if (!p.solid) return null;
  const footprint = FOOTPRINTS[p.prop];
  if (!footprint) return null;

  const swapped = p.rot === 90 || p.rot === 270;
  const w = (swapped ? footprint.d : footprint.w) * PROP_SCALE;
  const d = (swapped ? footprint.w : footprint.d) * PROP_SCALE;
  const cx = p.x * WORLD_SCALE;
  const cz = p.y * WORLD_SCALE;
  return { x1: cx - w / 2, y1: cz - d / 2, x2: cx + w / 2, y2: cz + d / 2 };
}

async function placeIndividually(scene: THREE.Scene, placements: PropPlacement[]): Promise<void> {
  await Promise.all(
    placements.map(async (p) => {
      const instance = await createPropInstance(p.prop);
      const sx = p.x * WORLD_SCALE;
      const sz = p.y * WORLD_SCALE;
      instance.position.set(sx, heightAt(sx, sz), sz);
      instance.rotation.y = (p.rot * Math.PI) / 180;
      scene.add(instance);
    })
  );
}

// Dresses both houses (house A generated by mirroring HOUSE_B_PROPS) plus the
// garden, and returns the AABB colliders for every solid prop so
// GameController can fold them into the CharacterController's collision
// list alongside the wall rects. Placement is fully deterministic - every
// instance's position/rotation/collider is derived directly from
// propManifest's static data, independent of which render path (instanced or
// individually-cloned) actually draws it.
export async function dressHouses(scene: THREE.Scene): Promise<{ solidRects: Rect[] }> {
  const houseAProps = HOUSE_B_PROPS.map(mirrorPlacement);
  const all = [...HOUSE_B_PROPS, ...houseAProps, ...GARDEN_PROPS];

  const solidRects: Rect[] = [];
  for (const p of all) {
    const rect = solidRect(p);
    if (rect) solidRects.push(rect);
  }

  const byProp = new Map<PropName, PropPlacement[]>();
  for (const p of all) {
    const list = byProp.get(p.prop);
    if (list) list.push(p);
    else byProp.set(p.prop, [p]);
  }

  await Promise.all(
    [...byProp.entries()].map(([prop, placements]) =>
      placements.length >= INSTANCE_THRESHOLD
        ? buildInstancedProps(scene, prop, placements)
        : placeIndividually(scene, placements)
    )
  );

  return { solidRects };
}
