import * as THREE from "three";
import { WORLD_SCALE, PROP_SCALE } from "../../constants";
import type { Rect } from "../../geometry/floorplan";
import { HOUSE_B_PROPS, GARDEN_PROPS, type PropPlacement, type Rot } from "./propManifest";
import { createPropInstance, FOOTPRINTS } from "./PropLibrary";

// Pre-scale floor plan width (see geometry/floorplan.ts), used only to mirror
// house B's placements onto house A - never multiplied by WORLD_SCALE itself.
const FLOORPLAN_WIDTH = 1600;

function mirrorRot(rot: Rot): Rot {
  return (((360 - rot) % 360) as Rot);
}

function mirrorPlacement(p: PropPlacement): PropPlacement {
  return { ...p, x: FLOORPLAN_WIDTH - p.x, rot: mirrorRot(p.rot) };
}

// Axis-aligned collider rect for one solid placement, in SCALED world
// coords: the meter footprint * PROP_SCALE, swapped when rotated a quarter
// turn, centered on the placement's scaled position.
function solidRect(p: PropPlacement): Rect | null {
  if (!p.solid) return null;
  const footprint = FOOTPRINTS[p.prop];
  if (!footprint) return null;

  const swapped = p.rot === 90 || p.rot === 270;
  const w = (swapped ? footprint.d : footprint.w) * PROP_SCALE;
  const d = (swapped ? footprint.w : footprint.d) * PROP_SCALE;
  const cx = p.x * WORLD_SCALE;
  const cz = p.y * WORLD_SCALE;
  return { x1: cx - w / 2, y1: cz - d / 2, x2: cx + w / 2, y2: cz + d / 2 };
}

async function placeAll(scene: THREE.Scene, placements: PropPlacement[]): Promise<Rect[]> {
  const rects: Rect[] = [];
  await Promise.all(
    placements.map(async (p) => {
      const instance = await createPropInstance(p.prop);
      instance.position.set(p.x * WORLD_SCALE, 0, p.y * WORLD_SCALE);
      instance.rotation.y = (p.rot * Math.PI) / 180;
      scene.add(instance);

      const rect = solidRect(p);
      if (rect) rects.push(rect);
    })
  );
  return rects;
}

// Dresses both houses (house A generated by mirroring HOUSE_B_PROPS) plus the
// garden, and returns the AABB colliders for every solid prop so
// GameController can fold them into the CharacterController's collision
// list alongside the wall rects. Placement is fully deterministic - every
// instance's position/rotation/collider is derived directly from
// propManifest's static data.
export async function dressHouses(scene: THREE.Scene): Promise<{ solidRects: Rect[] }> {
  const houseAProps = HOUSE_B_PROPS.map(mirrorPlacement);
  const [bRects, aRects, gardenRects] = await Promise.all([
    placeAll(scene, HOUSE_B_PROPS),
    placeAll(scene, houseAProps),
    placeAll(scene, GARDEN_PROPS),
  ]);
  return { solidRects: [...bRects, ...aRects, ...gardenRects] };
}
